# b1 zlog 部署
- hosts: all
  remote_user: opsuser
  become: yes
  gather_facts: yes
  vars:
    - ansible_python_interpreter: /root/.pyenv/versions/3.6.3/bin/python
    - gitrepo: git@github.com:PitayaDEV/B1Server_zlog.git
    - registry: registry.pitayacd.com:5000
    - imagename: registry.pitayacd.com:5000/game_debian:2.0
    - gitdir: /data/b1_zlog
    - platform_port: 8180
    - mysql_ip: 172.19.140.103
    - mysql_root_pwd: root.123
  tasks:
  - name: 检测LIMIT是否填写
    fail:
      msg: LIMIT没填！LIMIT没填！LIMIT没填！
    when: ansible_limit is not defined

  - name: 检测当前部署容器：b1_zlog是否已存在
    shell: |
      docker ps -a | grep -w b1_zlog
    register: judge_result
    ignore_errors: yes
    tags: test_exist

  - name: b1_zlog已存在，任务退
    fail:
      msg: "b1_zlog已存在，任务退"
    when: judge_result is success
    tags: test_exist

  - name: Docker镜像仓库 {{registry}} 登录
    docker_login:
       registry_url: "{{registry}}"
       username: pitaya
       password: PitaYa4108
       reauthorize: yes
    tags: dockerop

  - name: 拉取镜像
    docker_image:
      name: "{{imagename}}"
    tags: dockerop

  - name: 复制私钥
    copy:
      src: ./id_rsa
      dest: /root/id_rsa
      mode: 0400
    tags: gitop

  - name: 拉取git数据
    git:
      repo: "{{gitrepo}}"
      dest: "{{gitdir}}"
      key_file: /root/id_rsa
      ssh_opts: "-o StrictHostKeyChecking=no"
      force: yes
    tags: gitop

  - name: 删除私钥
    file:
      path: /root/id_rsa
      state: absent    
    tags: gitop,delkey

  - name: 配置 platform config 
    template: 
      src: ./file/zlog_config.xml.j2    
      dest: "{{gitdir}}/config/zlog_config.xml"
    tags: zlogconfig

  - name: 创建容器网络b1_net
    docker_network:
      name: b1_net
      driver: bridge
    tags: b1net

  - name: 创建b1zlog容器
    docker_container:
      name: b1_zlog
      image: "{{imagename}}"
      networks:
        - name: b1_net
      pull: no 
      volumes: 
        - "{{gitdir}}:/data"
        - "/etc/localtime:/etc/localtime:ro"
      published_ports: 
        - "{{platform_port}}:8180"
      entrypoint: ["bash","/data/start.sh"]
      state: started
      tty: yes
      restart_policy: always
    register: res
    tags: startzlog
